// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZ0LYSZtwalApA6hSArQwFzVGsxeAfUg',
    appId: '1:524455299014:android:005283a18b883dc0da94c7',
    messagingSenderId: '524455299014',
    projectId: 'the-network-app-6b78f',
    databaseURL: 'https://the-network-app-6b78f-default-rtdb.firebaseio.com',
    storageBucket: 'the-network-app-6b78f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD3ree-kC-VPKK_wTiu6hDR36rNnuOVv4',
    appId: '1:524455299014:ios:b96942b98a626575da94c7',
    messagingSenderId: '524455299014',
    projectId: 'the-network-app-6b78f',
    databaseURL: 'https://the-network-app-6b78f-default-rtdb.firebaseio.com',
    storageBucket: 'the-network-app-6b78f.firebasestorage.app',
    iosBundleId: 'com.garduation.theNetworkApp',
  );

}