// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv067b1znpBFTmyB1deCTqNVApaksUB8I',
    appId: '1:629425550281:android:447449baaa3026a72f6e18',
    messagingSenderId: '629425550281',
    projectId: 'the-network-8d7e2',
    databaseURL: 'https://the-network-8d7e2-default-rtdb.firebaseio.com',
    storageBucket: 'the-network-8d7e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMMMudF4rfPB5ghPcgnyziXeUHqJ3WXtM',
    appId: '1:629425550281:ios:c0cafb57c15d513d2f6e18',
    messagingSenderId: '629425550281',
    projectId: 'the-network-8d7e2',
    databaseURL: 'https://the-network-8d7e2-default-rtdb.firebaseio.com',
    storageBucket: 'the-network-8d7e2.firebasestorage.app',
    iosBundleId: 'com.garduation.theNetworkApp',
  );
}
